architect-team/architect-cli

bin/preinstall.sh, bin/run, package-lock.json, package.json, src/base.ts, src/commands/build.ts, src/commands/init.ts, src/commands/install.ts, src/commands/login.ts, src/commands/start.ts, test/launcher.test.ts, tslint.json
Handles the auth0 password grant
Stores access_token in the native credentials store
Created custom base Command
Added ArchitectClient for communication with hub/registry
=> Added `architect login` cmd

src/common/port-util.ts, src/common/protoc-executor.ts
- Failed port availability check due to lack of IPv6 check on ubuntu
- Generated gRPC stub files owned by incorrect user
=> Fixed some issues with using the CLI on ubuntu

src/base.ts
The token would get refreshed if expired on api requests, but not on docker cmds. This adds a check to every cmd to avoid login prompts.
=> Refresh the token before all cmds if expired

package-lock.json, src/commands/environments/create.ts
Added prompts to allow service accounts to be reused during kubernetes creation wizard
=> Added serviceaccount re-use prompt

src/dependency-manager/src/manager.ts
Same changes branched off of master
=> 93; add datastores to top-level nodes

src/commands/environments/destroy.ts, src/commands/init.ts
Closes https://gitlab.com/architect-io/architect-cli/issues/19
=> removing __version from architect files

README.md, package.json, src/commands/environments/create.ts, src/commands/environments/index.ts, src/commands/platforms/index.ts
Closes: https://gitlab.com/architect-io/hub-api/issues/84
=> add platform list command; add platform flow to env:create command

README.md, src/commands/environments/create.ts
Cleans up the environment:create flow per David's requested cases.
I'd like to harden this with more tests next time we're in here because I get the sense we're a bit under-covered here. Maybe we take that opportunity when we add ECS as a platform type.
=> streamline environment create for early onboarding

src/common/dependency-manager/local-manager.ts
Closes: https://gitlab.com/architect-io/hub-api/issues/67
=> change service call to match new endpoints on server

src/commands/environments/create.ts, src/common/utils/ecs-platform.utils.ts, src/common/utils/kubernetes-platform.utils.ts
Closes: https://gitlab.com/architect-io/hub-api/issues/91
=> add ECS support

src/commands/register.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/45
=> remove --no_build in favor of --image

src/commands/build.ts, src/commands/install.ts, src/commands/push.ts, src/commands/register.ts, src/common/dependency-manager/local-manager.ts, src/common/docker-compose/template.ts, src/common/utils/docker.ts, src/dependency-manager/src/service-config/base.ts, src/dependency-manager/src/service-config/builder.ts, src/dependency-manager/src/service-config/v1.ts, test/commands/build.test.ts
=> Allow for explicit architect.json path refs

src/commands/register.ts, src/common/utils/docker.ts
this is not necessary for the corresponding API changes to work, but includes better messaging for one error I came across this morning and a fix for an issue that was waiting to happen.
=> add account-not-found message and sanitize image tags

src/common/docker-compose/index.ts, src/common/docker-compose/template.ts, src/dependency-manager/src/environment-config/base.ts, src/dependency-manager/src/environment-config/v1.ts, test/mocks/calculator-compose.json, test/mocks/calculator-environment.json
```js
{
"dns": {
"searches": [
"testdomain.com"
]
},
"services": {
// ...
}
}
```
=> Added support for DNS searches

src/commands/deploy.ts, src/dependency-manager/src/manager.ts, test/commands/deploy.test.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/49
Closes https://gitlab.com/architect-io/architect-hub/-/issues/120
=> use validation api for cli local deploys

src/commands/deploy.ts
Closes https://gitlab.com/architect-io/hub-api/-/issues/154
=> 154 warning validation rules

src/dependency-manager/src/environment-config/base.ts, src/dependency-manager/src/graph/node/index.ts, src/dependency-manager/src/manager.ts, src/dependency-manager/src/service-config/base.ts, src/dependency-manager/src/service-config/v1.ts
Changed `default` type from your comments this AM. Also wanted to rename Parameter to ParameterValue for clarity.
=> rename Parameter to ParameterValue and make default type ParameterValue

src/commands/deploy.ts, src/commands/environments/create.ts, src/commands/push.ts, src/commands/register.ts, src/common/utils/docker.ts, src/common/utils/errors.ts, src/common/utils/offline.ts, src/common/utils/validation.ts
Closes https://gitlab.com/architect-io/hub-api/-/issues/137
Closes https://gitlab.com/architect-io/hub-api/-/issues/148
=> clean up error handling

src/common/docker-compose/index.ts
Reverts architect-team/architect-cli#167
=> Revert "Using architect nginx proxy"

src/commands/services/index.ts
Closes: https://gitlab.com/architect-io/hub-api/-/issues/166
=> stop using updated_at for business logic

.github/workflows/cli-rc.yml, src/dependency-manager/package-lock.json, src/dependency-manager/package.json, src/dependency-manager/src/utils/interpolation/expression-interpolator.ts
added `npm run build` of dependency-manager to the `test` github workflow.
=> add dependency-manage npm build to github workflow

src/commands/deploy.ts, src/common/utils/validation.ts, test/commands/deploy.test.ts
Came across this bad error message while I was testing https://gitlab.com/architect-io/hub-api/-/issues/224
The message was saying: `Environment name must be in the form my-account/environment-name` when it was an invalid platform name.
=> Fix validateNamespacedInput error message

src/dependency-manager/src/component-config/base.ts, src/dependency-manager/src/utils/refs.ts, src/dependency-manager/src/utils/slugs.ts, test/commands/config/get.test.ts, test/dependency-manager/utils/refs.test.ts
Fixes a bug I found with `-interfaces` refs; adds some more tests around url_safe_ref
=> add exception case for -interfaces; add tests to url_safe_ref

examples/database-seeding/README.md, package-lock.json, src/app-config/service.ts, src/commands/deploy.ts, src/commands/link.ts, src/commands/unlink.ts, src/common/dependency-manager/local-manager.ts, src/common/errors/missing-build-context.ts, src/dependency-manager/src/missing-required-param-error.ts, src/paths.ts, test/commands/link.test.ts, test/commands/unlink.test.ts
Closes https://gitlab.com/architect-io/hub-api/-/issues/218
=> remove all services references

src/dependency-manager/src/utils/refs.ts, test/dependency-manager/utils/refs.test.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/135
=> fix character limit bug; add tests

src/app-config/service.ts, src/commands/deploy.ts, src/commands/register.ts, src/common/utils/account.ts, test/commands/register.test.ts
Closes: https://gitlab.com/architect-io/hub-api/-/issues/185
=> add error handling for register

src/common/dependency-manager/local-manager.ts, src/dependency-manager/src/component-config/v1.ts, src/dependency-manager/src/manager.ts, src/dependency-manager/src/service-config/base.ts, src/dependency-manager/src/service-config/v1.ts, test/dependency-manager/interpolation.test.ts
Add architect context for components
=> Add deploy block to service spec

examples/basic-task/architect.yml, src/commands/deploy.ts, src/commands/init.ts, src/commands/task.ts, src/common/docker-compose/index.ts, src/common/docker-compose/template.ts, src/common/utils/environment.ts, src/dependency-manager/src/index.ts, src/paths.ts, test/commands/task.test.ts, test/dependency-manager/components.test.ts, test/dependency-manager/external.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/volumes.test.ts
Closes: Closes https://gitlab.com/architect-io/architect-cli/-/issues/157
=> add task:exec to CLI

src/commands/deploy.ts, src/commands/task.ts, src/dependency-manager/src/manager.ts, src/dependency-manager/src/utils/slugs.ts, test/commands/task.test.ts
Closes follow-ons from: https://gitlab.com/architect-io/architect-cli/-/issues/157
=> add account to task:exec command

src/app-config/config.ts, src/app-config/service.ts, src/commands/deploy.ts, src/commands/task.ts, src/common/docker-compose/index.ts, src/paths.ts, test/commands/task.test.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/162
=> add project_name to docker-compose to enable parallel runs

src/commands/platforms/create.ts, src/commands/platforms/destroy.ts, test/commands/platforms/create.test.ts
Closes: https://gitlab.com/architect-io/architect-hub/-/issues/238
=> disallow removing or adding Architect platforms

.github/workflows/register-examples.yml, docs/2-deployments/1-automated-previews.md, docs/2-deployments/2-gitops-releases.md
Closes: https://gitlab.com/architect-io/product/-/issues/94
Tested examples without unsafe-perm ref and that works now.
=> update gitops docs; remove unsafe-perm flag

src/commands/deploy.ts, src/commands/login.ts, src/commands/logout.ts, src/commands/register.ts, src/commands/task.ts, src/common/docker-compose/index.ts, src/common/utils/docker.ts, test/commands/deploy.test.ts, test/commands/login.test.ts, test/commands/logout.test.ts, test/commands/register.test.ts, test/commands/task.test.ts
Hold off on merging. Curious if these tests will pass. Docker daemon is required.
=> 194 ensure docker running

src/commands/deploy.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/169
=> 169; local deploy try/catch path, then assume component with 'latest' tag if none provided

.github/workflows/publish.yml
Reverts architect-team/architect-cli#365
=> Revert "use triggering branch for CLI release"

package-lock.json, src/commands/deploy.ts, src/commands/environments/destroy.ts, src/commands/platforms/create.ts, src/commands/platforms/destroy.ts, src/common/utils/pipeline.ts, test/commands/deploy.test.ts, test/commands/destroy.test.ts, test/commands/platforms/create.test.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/216
=> install applications on platform create

package-lock.json, src/commands/deploy.ts, src/commands/platforms/create.ts
Closes: https://gitlab.com/architect-io/hub-api/-/issues/378
=> use values.yml on remote deploys

src/commands/deploy.ts, src/commands/destroy.ts, test/commands/deploy.test.ts
@tjhiggins like I said, this works but I'm not sure it takes us in the right direction.
=> deploy command takes multiple components

src/common/docker-compose/index.ts, src/dependency-manager/src/graph/index.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/sidecar.test.ts
https://gitlab.com/architect-io/hub-api/-/issues/395
=> add inter-component depends_on back in

src/dependency-manager/src/graph/index.ts, test/dependency-manager/depends-on.test.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/240
=> add exception for external nodes in depends_on; more tests

src/commands/task.ts, test/commands/task.test.ts
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/238
=> 238; fix task:exec for components with instance_id

examples/react-app/architect.yml, examples/react-app/backend/Dockerfile, examples/react-app/frontend/Dockerfile, examples/react-app/frontend/Dockerfile.dev, src/app-config/service.ts, src/commands/deploy.ts, src/common/docker-compose/index.ts, src/common/docker-compose/template.ts, src/dependency-manager/src/spec/common/liveness-probe-spec.ts, test/commands/deploy.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/sidecar.test.ts
Add autoheal to restart unhealthy containers
Allow running of multiple traefik instances locally
Update react-app example to use liveness_probe
=> Set healthcheck for docker-compose

bin/check-version.js, package-lock.json, package.json, tsconfig.json
Reverts architect-team/architect-cli#401
=> Revert "Unsupported node version message"

src/common/docker-compose/index.ts
=> Fix bug with multiple $s

src/dependency-manager/src/manager.ts, src/dependency-manager/src/schema/config/component-config.ts, src/dependency-manager/src/schema/config/component-context.ts, src/dependency-manager/src/schema/spec-validator.ts, src/dependency-manager/src/schema/spec/component-spec.ts, src/dependency-manager/src/schema/spec/resource-spec.ts, src/dependency-manager/src/schema/spec/transform/component-transform.ts, src/dependency-manager/src/schema/spec/transform/resource-transform.ts, src/dependency-manager/src/utils/interpolation.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/schema/component-interpolation.test.ts
Make consumers an array of strings
Add test of parameter with object default
=> Support object interpolation

docs/0-getting-started/2-working-with-tasks.md, docs/1-components/5-tasks.md
This PR started as clarifying the relationship between tasks and components and the implications that has for deploying and using updated tasks. Though while working on that, I found that a simple guide through the Task development lifecycle helped more to establish the relationships and end-to-end process for developing a task.
=> Add docs task guide

docs/1-components/5-tasks.md, docs/5-reference/2-architect-yml.md, src/commands/init.ts, src/common/docker-compose/index.ts, src/dependency-manager/schema/architect.schema.json, src/dependency-manager/src/config/common-config.ts, src/dependency-manager/src/config/resource-config.ts, src/dependency-manager/src/config/service-config.ts, src/dependency-manager/src/spec/common-spec.ts, src/dependency-manager/src/spec/resource-spec.ts, src/dependency-manager/src/spec/service-spec.ts, src/dependency-manager/src/spec/transform/common-transform.ts, src/dependency-manager/src/spec/transform/resource-transform.ts, src/dependency-manager/src/spec/transform/service-transform.ts
Removed Volumes from the base Resources and added it only to Services since volumes are not supported by Sidecars nor Tasks.
=> Cleanup resource config volumes

src/commands/deploy.ts, src/common/errors/pipeline-errors.ts, src/common/utils/pipeline.ts, test/commands/deploy.test.ts, test/commands/platforms/create.test.ts
Added test case for polling timeout & improved typing throughout polling logic
=> Reset poll interval to 10 seconds instead of 1

src/commands/deploy.ts
This fixes a bug where a 302 would lead to a 404
=> Disable redirects when polling

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Adding a PR template to the repo. Hopefully this will provide us with better PRs.
Added a PR Template that is in this format
You are looking at it.
=> Add PR Template

src/commands/logs.ts
Small change to tooltip to remove local only usage in the description.
=> Updated since help tooltip.

src/common/docker-compose/index.ts
The last update to the health check worked, but it did not mimic kubernetes exactly. This should bring us closer to the way services will act remotely.
Kubernetes ahs 3 policy types for Restart. Always, OnFailure and Never. So we will mimic the Always and OnFailure behavior which in this instance is essentially the same thing.
1) Removed the health check code
2) Auto restart when unhealthy
3) If the container dies always restart
4) No limits on the amount of restarts
Same tests as https://github.com/architect-team/architect-cli/pull/550
=> Modified health check

src/commands/dev.ts, src/commands/register.ts, src/common/dependency-manager/local-manager.ts, src/dependency-manager/graph/type.ts, src/dependency-manager/manager.ts, src/dependency-manager/secrets/secrets.ts, src/dependency-manager/secrets/type.ts, test/dependency-manager/components.test.ts, test/dependency-manager/graph.test.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/sidecar.test.ts, test/dependency-manager/template.test.ts, test/dependency-manager/validation.test.ts
Add types for secrets/graph options
=> Cleanup manager logic

src/commands/register.ts, src/common/utils/docker-buildx.utils.ts, test/commands/register.test.ts, test/utils/mocks.ts
Issue https://gitlab.com/architect-io/architect-cli/-/issues/430.   
architect-local register . --architecture arch1 --architecture arch2
=> 430 platform flag

src/architect/secret/secret.utils.ts, src/architect/user/user.utils.ts, src/commands/secrets/download.ts, src/commands/secrets/upload.ts, test/commands/secrets/download.test.ts, test/commands/secrets/upload.test.ts, test/mocks/secrets/account-secrets.yml, test/mocks/secrets/environment-secrets.yml, test/utils/mocks.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/405.   
Commands to test this PR can be found in the issue above.
=> 405 secrets download and upload

src/commands/register.ts
Use console.time for better formatting
=> Cache all stages of build

src/commands/platforms/create.ts, src/common/utils/kubernetes-platform.utils.ts
Referenced https://github.com/digitalocean/doctl/blob/main/commands/auth.go#L122
=> adding config dir env var in case where a kubeconfig command is looking for configuration

src/app-config/service.ts
please see https://gitlab.com/architect-io/architect-cli/-/issues/469
=> return empty when reading empty json

src/base-command.ts, src/sentry.ts, test/commands/logout.test.ts
please see https://gitlab.com/architect-io/architect-cli/-/issues/471
=> add try/catch to file io and sentry end transactn

.gitconfig, git_hooks/pre-commit
This is what happens if you purposefully break a test: 
This is a screenshot of me committing the changes in this PR which ran the pre-commit hook:
=> Pre-commit hook to run `npm run check`

src/commands/exec.ts
please see https://gitlab.com/architect-io/architect-cli/-/issues/462
Test cases in progress.
=> exit with remote exec error codes

package-lock.json, package.json, release.config.js, yarn.lock
When we push to main this will backport those changes to rc.
=> Add support for backmerging on push to main

src/commands/exec.ts
If the process's stdin is a TTY, even if --tty is not desired as part of the exec command itself, we can use `process.stdin.pipe(inputTransform).pipe(websocket);` to send input if it exists through the websocket. This is what happens during `architect exec /bin/sh` for example. 
If the process's stdin _isnt_ a TTY, which happens with a command like `architect exec -a test-tyler-0 -e example-environment -- cat < test-script.sh` where we're piping input to exec, it's possible for stdin to close before the websocket gets the data and passes back the response. If this happens, the command just doesn't work at all, so `{ end: false }` prevents the websocket from closing until the `outputTransform` eventually gets a success status.
The other issue was related to setting `tty=true` in the …
=> Fix issue with commands run in no-tty but with stdin available exiting prematurely due to stdin closing

package-lock.json, package.json, patches/@oclif+core+1.9.0.patch, src/architect/account/account.utils.ts, src/architect/environment/environment.utils.ts, src/architect/platform/platform.utils.ts, src/commands/components/index.ts, src/commands/components/versions.ts, src/commands/deploy.ts, src/commands/destroy.ts, src/commands/dev.ts, src/commands/doctor.ts, src/commands/environments/create.ts, src/commands/environments/destroy.ts, src/commands/environments/index.ts, src/commands/exec.ts, src/commands/init.ts, src/commands/link.ts, src/commands/logs.ts, src/commands/platforms/create.ts, src/commands/platforms/destroy.ts, src/commands/platforms/index.ts, src/commands/register.ts, src/commands/secrets/download.ts, src/commands/secrets/upload.ts, src/commands/task.ts, src/commands/unlink.ts, src/commands/validate.ts, src/sentry.ts
Update sentry to only send docker/file data for errors
=> Add sensitive flag to oclif flag type

src/commands/register.ts
Issue: https://gitlab.com/architect-io/architect-cli/-/issues/475
=> Allow register without build

src/architect/account/account.utils.ts
Please see: https://gitlab.com/architect-io/architect-cli/-/issues/486
=> no local selection when docker is unavailable

src/commands/dev.ts
Closes issue: https://gitlab.com/architect-io/architect-cli/-/issues/485.
=> Prompt user for available port

src/commands/exec.ts
This was happening because we piped the websocket output to a `stream.Transform`, which is a `Duplex` stream that is readable and writable. We never actually read from this stream, which meant the read buffer eventually fills up. This causes writes to accumulate in a buffer until the stream is read from -- which never happens.
Turning this into a `stream.Writable` fixes this issue - we never need to read anything from this stream so now we're not storing anything in a useless buffer and can process all the data.
=> Fix exec hanging after it processes too much data

src/commands/exec.ts
Tested this on mac, windows (powershell + cmd), and in Linux via wsl2 and on each system resizes are working correctly. The initial size of the window is also correct now 🥳.
Fixes issues with programs like vim, less, etc. that require knowledge of the terminal size in order to draw themselves correctly, and without passing a size explicitly it would fall back to a default size and provide a weird experience.
Note that kubernetes on the server side handles backwards compatibility - if somebody is running a (very very) old cluster that doesn't support resize events, this just gets ignored. The kubectl client always sends this data regardless, so we should be safe to do the same.
=> Handle terminal resize events in exec

src/app-config/service.ts, src/base-command.ts, src/commands/deploy.ts, src/commands/dev.ts, src/commands/exec.ts, src/common/utils/oclif.ts, src/sentry.ts, test/.mocharc.yml, test/commands/config/get.test.ts, test/commands/config/view.test.ts, test/commands/deploy.test.ts, test/commands/environments/index.test.ts, test/commands/exec.test.ts, test/commands/platforms/create.test.ts, test/commands/task.test.ts, test/test-setup.ts
Fixing the last two flags I missed in the original pr: https://github.com/architect-team/architect-cli/pull/683 to complete the refactor.
=> convert deployCommand auto-approve

README.md
reapply changes to logo to display dark/light logo based on github theme here:
https://github.com/architect-team/architect-cli/commit/3b43dec4c58e012e4b94741f189ce4b2cd4f6889
=> update readme top logo

src/architect/project/project.utils.ts, src/commands/init.ts, src/common/utils/prompt-utils.ts
Opening PR to have a place for review and feedback.
Please see https://gitlab.com/architect-io/architect-cli/-/issues/505
=> 505 slow down initial init

src/commands/dev/list.ts
=> examples typo dev:list

src/commands/dev/list.ts
Somehow managed to add the new `@RequiresDocker` and forgot to use it on the new `dev:list` command
=> dev:list requires docker and compose

src/commands/dev/index.ts, src/common/docker-compose/index.ts, test/commands/dev/index.test.ts
Fixes architect dev in gitlab CI
=> Add traefik default cert via envs as opposed to volume

src/commands/dev/index.ts
=> Sanitize the component name to remove /

src/commands/dev/index.ts
=> fixing spelling

src/common/utils/agent-platform.utils.ts
Just clean up some of the code for agent creation. This also fixes a bug where the crb was not being generated on the M1. 
Tested on M1, WSL2 and DO.
All tests still pass.
=> Clean up agent install

src/app-config/auth.ts
Updated auth0 check to include the dev auth0 tenant for https://gitlab.com/architect-io/architect-hub/-/issues/546
Follow the steps on the ticket at https://gitlab.com/architect-io/architect-hub/-/issues/546#note_1111402986 to test
=> updates for dev auth tenant

src/dependency-manager/spec/service-spec.ts, test/dependency-manager/validation.test.ts
I tried setting memory to 0.75 and it yelled at me during the terraform apply. This avoids ever getting that far and realizing the value is incorrect.
=> fix(spec): Add validation for replicas/scaling

examples/kafka/architect.yml, examples/kafka/publisher/Dockerfile, examples/kafka/publisher/package-lock.json, examples/kafka/publisher/package.json, examples/kafka/subscriber/Dockerfile, examples/kafka/subscriber/package-lock.json, examples/kafka/subscriber/package.json
Fix error when running on M1.
Updated Kafka and Zookeeper images in architect.yml
Manual tests
Blog post that references this code will be updated. 
N/A
=> Update Kafka and Zookeeper image versions

src/common/docker-compose/index.ts
- `service_ref_map` isn't needed anymore because the output of `docker inspect` has all the information we need - however, it's still used to figure out what services we are watching, so it's been changed to a `Set`
- `container_map` was moved into the `try` because it can fail if it gets run while `docker compose up` is happening (the sequence `docker ps -aq` runs (getting the previous list of containers) -> `docker compose up` -> `docker inspect` would cause errors, now we just retry until it works)
- `full_service_name` was being set to what we previously called `service_ref`, this has been updated
- `last_health_failure_map` keeps track of when the last health log happened so we don't print the same failure twice, and users get 1 logged error each time the health check runs (based on …
=> Fix container health crashes and log liveness probe once per log line

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Adds issue templates to assist users in creating issues and to help us get useful information to help them
* Added bug report and feature request templates
=> adding issue templates for CLI

.github/workflows/test-deploy.yml
Adding `ACCOUNT_NAME` for environment create part of remote deployment
=> Workflow trigger update

.github/workflows/test-deploy.yml
Updates remote deployment test to pass when merging a branch to `main`
Checks originally passed in the testing PR https://github.com/architect-team/architect-cli/pull/784
Superset workflow: https://github.com/architect-team/architect-cli/actions/runs/3707726296
=> Remote deployment workflow updates

package-lock.json, package.json, src/app-config/auth.ts, src/base-command.ts
Add expiration window to combat race condition
Upgrade simple-oauth2
=> Add timeout to getToken

.eslintignore, .husky/pre-commit, lint-staged.config.js, package-lock.json, package.json, yarn.lock
Switch over to `lint-staged` which has better support for handling out git hooks.
Ran local commits to make sure everything works.
=> Lint staged

package-lock.json, package.json, src/app-config/config.ts, src/app-config/service.ts, src/base-command.ts, src/commands/config/set.ts, src/commands/dev/index.ts, test/config.json, yarn.lock
Adds the posthog SDK so we can understand the usage patterns of folks on our CLI.
Introduces the posthog SDK can captures basic command event details.
=> Init posthog SDK

.gitignore, package-lock.json, package.json, src/app-config/auth.ts, src/app-config/config.ts, src/app-config/posthog.ts, src/app-config/service.ts, src/base-command.ts, src/commands/dev/index.ts, src/paths.ts, src/sentry.ts, yarn.lock
We had some issues attributing events to individual sessions making it hard to measure performance of our longer running commands.
Added tracking event to capture command start time, and updated capture method to use anonymous id.
=> Fixed analytics

src/commands/dev/restart.ts, test/commands/dev/restart.test.ts
Fixes: https://gitlab.com/architect-io/architect-cli/-/issues/628
=> Default --build to true

src/commands/dev/index.ts, src/common/docker-compose/index.ts, src/common/docker-compose/template.ts, src/common/docker/buildx.utils.ts, test/commands/dev/index.test.ts, test/dependency-manager/components.test.ts, test/dependency-manager/external.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/reserved-names.test.ts
Reverts architect-team/architect-cli#792
=> Revert "automatically cleaning up cached data that's older than 7 days"

bin/run
Discussion here - https://github.com/architect-team/architect-cli/pull/864
=> Update ./bin/run to hide ExperimentalWarning

src/commands/dev/index.ts
Make sure we pipe stderr to stderr
Make sure we pipe stderr to stderr
Showing errors it did not show before
=> Add in stderr to logs

src/dependency-manager/config/service-config.ts, src/dependency-manager/spec/service-spec.ts, src/dependency-manager/spec/transform/service-transform.ts, test/mocks/superset/architect.yml
Closes https://gitlab.com/architect-io/architect-cli/-/issues/642
* Adds `termination_grace_period` to the service config
=> termination grace period

README.md, architect-yml.md, package-lock.json, package.json, src/commands/clusters/create.ts, src/commands/clusters/destroy.ts, src/commands/clusters/index.ts, src/common/docker-compose/converter.ts, src/common/utils/deploy.utils.ts, src/common/utils/secret/helper.ts, src/dependency-manager/config/service-config.ts, src/dependency-manager/schema/architect.schema.json, src/dependency-manager/spec/service-spec.ts, src/dependency-manager/spec/transform/service-transform.ts, test/commands/dev/index.test.ts, test/commands/init.test.ts, test/mocks/init-compose.yml, test/mocks/superset/architect.yml, yarn.lock
A short description of what this PR intends to accomplish. This should proivde context as to why these changes are necessary.
Provide a list of any changes that that have been made to accomplish the goal stated above.
Provide a list of steps that can be used to test each of your changes. Any special setup should be called out explicitly. Examples of test commands or URLs can help when dealing with a CLI or API.
If this is a new feature or changes functionality, provide a link to the ticket for documentation additions or updates.
If any UX has changed a picture should be attached to show the new user experience. Any CLI tooling changes count as a UX change.
=> Production Release

src/commands/dev/index.ts
https://github.com/docker/compose/releases/tag/v2.17.2
Also fix issue with some compose logs getting lost
=> Latest version of docker-compose broke --timeout

test/commands/clusters/create.test.ts, test/commands/platforms/create.test.ts
Fixes tests that had unfortunate conflicts based on two previous PRs - 
* https://github.com/architect-team/architect-cli/pull/887
* https://github.com/architect-team/architect-cli/pull/882
=> updating tests to fix unfortunate conflicts

src/architect/account/account.utils.ts
This can happen if a user has an invalid token (for some reason) or an expired token. We'll attempt to hit the accounts endpoint, it will return an error, and the exec command would silently fail and not give the user any explanation.
If this happens now, it'll warn the user that they need to login, but still allow them to select the local dev environment and exec locally as normal.
Ticket: https://gitlab.com/architect-io/architect-cli/-/issues/660
=> Catch error when trying to hit accounts endpoint, fallback to allowing user to select a local env

src/commands/clusters/create.ts, src/commands/register.ts, src/dependency-manager/spec/resource-spec.ts, src/dependency-manager/spec/service-spec.ts, src/dependency-manager/spec/task-spec.ts, src/dependency-manager/spec/utils/json-schema-annotations.ts, test/dependency-manager/spec/component-spec.unit.test.ts, test/dependency-manager/spec/partials/root/services/_image/image.yml, test/dependency-manager/spec/partials/root/services/basic-service.yml, test/dependency-manager/spec/partials/root/services/service-with-command-array.yml, test/dependency-manager/spec/partials/root/services/service-with-command.yml, test/dependency-manager/spec/partials/root/services/service-with-entrypoint.yml, test/dependency-manager/spec/partials/spec-test-harness.ts, test/dependency-manager/validation.test.ts
**Merge only after https://gitlab.com/architect-io/hub-api/-/merge_requests/760 and https://gitlab.com/architect-io/hub-api/-/merge_requests/761**
Reverts architect-team/architect-cli#890
=> Revert "Revert "throwing error when build used with image, test updates""

src/dependency-manager/spec/component-spec.ts
A short description of what this PR intends to accomplish. This should proivde context as to why these changes are necessary.
Provide a list of any changes that that have been made to accomplish the goal stated above.
Provide a list of steps that can be used to test each of your changes. Any special setup should be called out explicitly. Examples of test commands or URLs can help when dealing with a CLI or API.
If this is a new feature or changes functionality, provide a link to the ticket for documentation additions or updates.
If any UX has changed a picture should be attached to show the new user experience. Any CLI tooling changes count as a UX change.
=> Fix issue with spec validation

src/commands/register.ts, src/dependency-manager/spec/component-spec.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/spec/partials/root/dependencies/multiple-dependencies.yml, test/dependency-manager/validation.test.ts
A short description of what this PR intends to accomplish. This should proivde context as to why these changes are necessary.
Provide a list of any changes that that have been made to accomplish the goal stated above.
Provide a list of steps that can be used to test each of your changes. Any special setup should be called out explicitly. Examples of test commands or URLs can help when dealing with a CLI or API.
If this is a new feature or changes functionality, provide a link to the ticket for documentation additions or updates.
If any UX has changed a picture should be attached to show the new user experience. Any CLI tooling changes count as a UX change.
=> Tag secret spec
