package-lock.json, package.json, src/commands/start.ts, src/common/protoc-executor.ts
Moved protoc execution code to a new namespace and copied the proto files to the tmp directory on the host under folders matching the name of the service. See https://github.com/architect-team/python-launcher/issues/1#issuecomment-461635733 for details.
=> Updated to latest python launcher and used module references for python3

src/commands/deploy.ts
Added a new `--service` parameter that can accept paths to additional services to start:
Example:
```bash
$ architect deploy --local --service ../addition-service --service ../division-service
```
=> Allowed for startup of multiple services at once

src/commands/deploy.ts
Had to move the for loop shown inside the condition to see whether or not the object already exists. Currently, prior additions to this object are being overwritten on second passes through the loop.
=> Prevented override of subscriptions in CLI

src/commands/environments/create.ts
Previously, if the user hasd set their kubetcl context to a particular namespace, architect was creating serviceaccounts scoped only to that namespace. Those (rightfully) failed our `can-i` check and prevented the creation of an environment.
This commit changes the scope of the architect CLI's kubectl execs to use the `default` namespace.
=> use default namespace regardless of what the user has set locally

package.json
Fix to pin inquirer before this breaking change: 
https://github.com/SBoudrias/Inquirer.js/pull/891
=> pinning inquirer to a version that works with non-tty

src/common/dependency-manager/local-manager.ts, src/common/docker-compose/index.ts, src/dependency-manager/src/service-config/base.ts, src/dependency-manager/src/service-config/v1.ts, test/dependency-manager/builder.test.ts
This PR is two updates: 
1) Fixes a bug where port value in the service was ignored in the docker-compose file 
2) Fixed a compose issue where data volumes were not supported `/myapp/directory`
=> Adding port mapping to config and supported data volumes

.gitmodules
I made this a submodule instead of copying the contents because the repo is a fork of the parent. It seemed easier to maintain the fork contents as a properly forked repository.
=> Added submodule in examples folder to hipster-shop demo

src/dependency-manager/src/index.ts, src/dependency-manager/src/service-config/base.ts, src/dependency-manager/src/service-config/v1.ts
This adds digest to ServiceConfig and adds the ComponentConfig/Builder to the exports.
It doesn't do anything else that we talked about. Those will be with the rest of my `register` branch. Just wanted to get these in so I could reference them.
=> add digest to serviceconfig

src/commands/register.ts, src/common/errors/missing-build-context.ts
* Hides the flags for registering multiple components at once from the generated docs (via `hidden` flag)
* Adds an argument to the CLI register command to accept the path to a component as the primary arg (e.g. `architect register ./path/to/component`)
=> Added optional arg to register components instead of needing the flag

src/commands/deploy.ts
Updated the deploy command to dump and execute yml instead of json for docker-compose. This is largely to make the outputs more human-readable.
=> Dump yml instead of json for docker-compose output

src/commands/platforms/create.ts, test/commands/platforms/create.test.ts
Seems we couldn't register the public platform from the CLI. This fixes that.
=> Fixed public platform specification

src/dependency-manager/src/utils/refs.ts, test/dependency-manager/utils/refs.test.ts
@tjhiggins we had taken out the `max_length` option from `url_safe_ref()`. I'm having a hard time remembering exactly why, but I think we decided we didn't want the service names variable across docker-compose, kubernetes, aws.
I'm adding it back in so we can use it for resource naming in ECS.
Once you merge this, I'll test and submit the PR for the API.
=> add max length option back into Refs.url_safe_ref

examples/basic-task/architect.yml, src/commands/register.ts, src/common/dependency-manager/local-manager.ts, src/common/docker-compose/index.ts, src/dependency-manager/src/component-config/base.ts, src/dependency-manager/src/component-config/builder.ts, src/dependency-manager/src/component-config/v1.ts, src/dependency-manager/src/environment-config/base.ts, src/dependency-manager/src/graph/index.ts, src/dependency-manager/src/graph/node/task.ts, src/dependency-manager/src/manager.ts, src/dependency-manager/src/service-config/v1.ts, src/dependency-manager/src/task-config/base.ts, src/dependency-manager/src/task-config/v1.ts, src/dependency-manager/src/utils/validation.ts, test/dependency-manager/components.test.ts
@tjhiggins - how does this look directionally? Once you think it's safe to merge, I can get to work on the API.
I've left a number of `TODO:84` scattered here that we're going to want to return to (mostly interfaces and references), but theoretically what I have in this PR should give us enough to go on to get TaskNodes deploying remotely.
=> add tasks to component spec

src/dependency-manager/src/index.ts
@tjhiggins we also need to export the TaskNode/Config.
Try merging this one in and let's hope tests pass. If not, I think we need to resolve (or remove) that nondeterministic test `deploy.test.ts#describe('local deploy environment', ...)` because the release will block me this AM. I'm still moving forward on the terraform side but soon I'll want to bridge them.
=> export TaskNode and TaskConfig

src/dependency-manager/README.md, src/dependency-manager/package-lock.json, src/dependency-manager/package.json, src/dependency-manager/src/spec/v1-component-spec.ts
This includes everything needed to generate a json schema file from a typescript interface that I've included in the repo. 
Some things that could be done once this gets merged in:
* Publish a PR to the schemastore that uses the generated schema spec (must be done manually, and I will do once this gets merged in)
* Extend the interface that powers this schema gen as part of our config classes so that the interface becomes functionally useful
* Use something like AJV to validate incoming yaml files instead of having to use the class-validator annotations. AJV uses json schema and has sponsorship from Mozilla ensuring its stability: https://github.com/ajv-validator/ajv/
=> Added typescript interface representing the component spec

src/dependency-manager/src/manager.ts, src/dependency-manager/src/spec/common/interface-spec.ts, src/dependency-manager/src/spec/common/interface-v1.ts, src/dependency-manager/src/spec/v1-component-spec.ts, test/dependency-manager/interfaces.test.ts
Added optional support for HTTP basic auth `username` and `password` on service interfaces, both statically and as parameters. This allows us to carve out things like SMTP or database services that require username and password for authentication into separate components. That way the credentials can live with the component and upstream can get access to a fully resolvable `url` value that includes said credentials (e.g. `smtp://user:pass@host:port` or `postgres://user:pass@host:port`, etc.).
=> Added support for HTTP basic auth on interfaces

src/dependency-manager/src/manager.ts, test/dependency-manager/external.test.ts
The port values `80` and `443` are already the defaults for HTTP and HTTPS requests coming from any HTTP client and they don't need to be cited explicitly. Furthermore, including them causes weird behavior when storing and retrieving cookies. Funny enough, cookies associated with `http://app.localhost:80` are not retrievable by `http://app.localhost`. Since the browser already strips these ports, browsers are NEVER able to retrieve cookies associated with URLs that include the default port values. 
This ticket strips the port from the interface `url` value whenever they match the default for the HTTP or HTTPS protocol respectively.
=> Stripped the default browser ports from url value

src/dependency-manager/src/manager.ts, src/dependency-manager/src/spec/component/component-transformer.ts, src/dependency-manager/src/spec/component/component-v1.ts, src/dependency-manager/src/utils/interpolation.ts, test/dependency-manager/interfaces.test.ts
Noticed that the recent basic auth interfaces feature didn't work for calling dependency interfaces. Added that in and added test coverage.
=> Ensured that dependency calls support basic auth where applicable

docs/0-getting-started/0-introduction.md, docs/2-deployments/0-local-development.md, examples/database-seeding/README.md, examples/hello-world/README.md, examples/hot-reloading/README.md, examples/nestjs-microservices/simple/README.md, examples/react-app/README.md, examples/stateful-component/README.md, examples/stateless-component/README.md, package-lock.json, src/common/dependency-manager/local-manager.ts, src/common/docker-compose/index.ts, test/commands/deploy.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts
Backport for: https://gitlab.com/architect-io/architect-cli/-/issues/213
@tjhiggins- I made the branch `hotfix/v0.8` off of the commit with the `v0.8.6` tag. Once you merge this you should just be able to tag the resulting commit for the new release. I'm assuming `v0.8.7`.
I named this branch with the above naming assumption and that all subsequent releases from the master branch should probably increment the minor version (ie. our traefik CLI release will be `v0.9.0`). Any subsequent `0.8.n` hotfixes (god forbid there are any more) should end up on this `hotfix/v0.8` branch.
=> change .localhost to .arc.localhost; hotfix back-port

src/commands/task.ts, test/commands/task.test.ts
@tjhiggins fixed the local task:exec and the tests here.
Note the mocha issue is still outstanding: if an exception occurs in the `describe` block, that test exits without any warning and the remainder of the tests in that files simply don't run.
There are several mocha github issues related (looks like error handling has historically been a a problem in various situations), but none for this specific situation. Should we create an issue there?
=> fix task:exec bug, fix tests

src/common/docker-compose/index.ts, src/dependency-manager/src/graph/index.ts, src/dependency-manager/src/index.ts, src/dependency-manager/src/manager.ts, src/dependency-manager/src/spec/component/component-v1.ts, src/dependency-manager/src/spec/resource/resource-config.ts, src/dependency-manager/src/spec/resource/resource-v1.ts, src/dependency-manager/src/utils/validation.ts, test/commands/deploy.test.ts, test/dependency-manager/components.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/sidecar.test.ts, test/dependency-manager/validation.test.ts
CLI/dependency-manager component of: https://gitlab.com/architect-io/hub-api/-/issues/395
I'll test and open a PR for the cloud-api when this is merged.
Note: this also contains some `"restart": "always",` fixes for tests that were failing.
=> 395 explicit depends on

docs/1-configuration/0-architect-yml.md, docs/1-configuration/1-services.md, src/common/dependency-manager/local-manager.ts, src/dependency-manager/src/manager.ts
@tjhiggins note: I tweaked the instance_id. I didn't realize this gets used for the component graph too, not just on local deployments. I don't think it matters but I figured `*-component` makes more sense than `*-local`
=> add docs for depends_on; tweak instance_id for components

src/commands/deploy.ts, src/common/docker-compose/index.ts, src/common/docker-compose/template.ts
Related to this in testing compose v2, I found that the `--compatibility` flag that we use is no longer supported and the command will fail if we leave that in there. It looks like that's required for Windows or something? What are your thoughts on that conflict @tjhiggins?
=> integer retries for compose v2 compatibility

src/commands/platforms/index.ts
This PR includes the Account column on the list of platforms
```
% architect platforms
┌───────────┬────────────┬─────────────────────────────────────────┬────────────┬─────────────────────┬──────────────────────────┬──────────────────────────┐
│ Name      │ Account    │ Host                                    │ Type       │ Credentials         │ Created                  │ Updated                  │
├───────────┼────────────┼─────────────────────────────────────────┼────────────┼─────────────────────┼──────────────────────────┼──────────────────────────┤
│ local-dev │ my-account │ https://kubernetes.docker.internal:6443 │ KUBERNETES │ Encrypted on Server │ 2021-08-11T22:49:18.956Z │ 2021-08-11T22:49:18.956Z │
└───────────┴────────────┴─────────────────────────────────────────┴────────────┴ …
```
=> 281 include account on platform list

src/base-table.ts, src/commands/environments/index.ts, src/commands/platforms/destroy.ts, src/commands/platforms/index.ts, src/common/utils/localized-timestamp.ts
This change makes timestamps a little more human readable:
```
% architect platforms                               
┌───────────┬──────┬────────────┬─────────────────────┬────────────────────────────┬────────────────────────────┐
│ Name      │ Host │ Type       │ Credentials         │ Created                    │ Updated                    │
├───────────┼──────┼────────────┼─────────────────────┼────────────────────────────┼────────────────────────────┤
│ local-dev │      │ KUBERNETES │ Encrypted on Server │ 08/11/2021, 3:49:18 PM PDT │ 08/11/2021, 3:49:18 PM PDT │
└───────────┴──────┴────────────┴─────────────────────┴────────────────────────────┴────────────────────────────┘
```
vs the current
```
% architect platforms
┌───────────┬──────┬────────────┬─────────────────────┬────────────── …
```
=> 282 localized timestamps

src/commands/deploy.ts, src/common/dependency-manager/local-manager.ts, test/dependency-manager/interfaces.test.ts
This will automatically map any unmapped interfaces when deployed locally. Implicit interface mapping is disabled if you deploy locally with the `--production` flag. Deploying multiple instances of a component will also cause implicit interface mappings to be disabled since we can't map a single interface to multiple components.
=> Local deploy maps all available interfaces

src/commands/register.ts, test/commands/register.test.ts
@tjhiggins the regex was not matching newlines so build args with newlines (ie an ssh private key) were being cut off.
=> allow build args with newline

src/app-config/config.ts, src/commands/components/index.ts, src/commands/components/versions.ts, src/commands/deploy.ts, src/commands/destroy.ts, src/commands/environments/create.ts, src/commands/environments/destroy.ts, src/commands/environments/index.ts, src/commands/init.ts, src/commands/platforms/create.ts, src/commands/platforms/destroy.ts, src/commands/platforms/index.ts, src/commands/register.ts, src/commands/task.ts, src/common/utils/account.ts, test/commands/config/get.test.ts
Now you can set an account config to use by default:
```
architect config:set account my-org
```
This behaves similarly to the `ARCHITECT_ACCOUNT` environment variable, and can be overwritten by providing the account flag.
=> Add the "account" configuration so users can set a default account

src/commands/logs.ts
When piping log output to a downstream command, the current application will crash unless the raw flag is set. This is due to the nodejs not setting the stdout columns data in. Without this data the formatting system produces a NaN for the allowed column length and breaks.
The easy solution is to force the raw mode if we detect the caller is not in tty mode. This does cause a flag to be set when the user did not explicitly set it, but in this instance I think that's okay.
=> Fix issue preventing logs from being pipable.

src/dependency-manager/src/spec/utils/spec-validator.ts
According to the docs, the current task spec allows a task with an empty schedule. This allows a user to register a task that they will trigger manually. However at the moment the architect validate command fails if you use an empty schedule. However it does work if the schedule is removed completely.
When checking for a valid cron in the schema we also pass an empty string now.
This changes the default behavior of what a valid cron schedule is. At the moment it appears that only the task spec uses this, but if another part of the spec requires a cron and uses the cron field, it could lead to weird behavior.
=> Allow empty string for scheudle.

README.md, docs/0-getting-started/0-introduction.md, docs/0-getting-started/2-working-with-tasks.md, docs/1-components/7-local-configuration.md, examples/database-seeding/README.md, examples/gcp-pubsub/README.md, examples/hello-world/README.md, examples/hot-reloading/README.md, examples/nestjs-microservices/simple/README.md, examples/react-app/README.md, examples/scheduled-tasks/README.md, examples/stateful-component/README.md, examples/stateless-component/README.md, src/commands/task.ts, test/commands/task.test.ts
This PR follows up the changes made to the CLI to remove the --local flag. 
All docs/examples have been updated to remove the usage of the ``` architect deploy --local``` command and replace it with the ```architect dev``` command. At the same time I removed some of the deprecated flags such as ```--production```.
Viewed each change in a Markdown viewer to make sure the formatting looked correct. Otherwise discussed any possible confusion a user may have over the intent of the documentation with @tjhiggins.
=> Updated all the docs and examples that used deploy -l

src/architect/account/account.utils.ts, src/commands/logs.ts, src/common/docker-compose/index.ts
This PR adds support for querying logs for a local service. The following assumptions are now made.
1. If an environment flag is set then we check if it matches a local env first. If it does we assume the user is looking for a local service.
2. If an account flag is set we automatically assume the user is looking for a remote service.
3. If no flags are set we ask for the account the user is looking for. We add a new option called "dev (Local Machine)" that the user can select for a local service.
NOTES: The since flag does not work locally and is ignored. While kubernetes supports since, docker does not. We could implement this feature ourselves but it did not seem worthwhile in the short term.
1. Added the concept of a local account and the ability to check if an account is a local …
=> Added support for local logs.

src/commands/dev.ts
Both the logs and exec command rely on our config folder to act as a source of truth about active environments. In order for that to remain true we need that folder to only have active environments. This code cleans up docker compose files after a dev command has completed to keep the source of truth valid.
Remove the docker compose file once the docker containers have been cleaned up.
1. Run ```architect dev``` and create an env called cloud
2. Note the file ```~/.config/architect/architect/docker-compose/cloud.yml``` exists
3. Terminate the ```architect dev``` command
4. Not the file ```~/.config/architect/architect/docker-compose/cloud.yml``` does not exists
=> Remove compose file on end of dev command.

src/architect/account/account.utils.ts, src/commands/exec.ts, src/commands/logs.ts, src/common/docker-compose/index.ts
This fixes 2 issues.
1) When an service is passed in it will never be found.
2) Made the commands more versatile with docker compose versions.
```
architect-local exec -it -e cloud cloud-api -- sh
architect-local exec -it -e cloud -- sh
architect-local exec -it -- sh
```
=> Fix issue where passing the service name in does not work

src/commands/unlink.ts
If no value is given for the unlink command it will attempt to use the folder name as the service name. This diff changes the behavior to
1) If no resource is given then use the name from the local architect file.
2) If an architect file path is given use the name from that file.
3) All other strings are processed as is.
=> Fixed bug where unlink does not work with account name.

.github/workflows/publish.yml, bin/readme, bin/readme.cmd, package.json, src/commands/logs.ts
When changes were made to migrate to Oclif 2 our readme was not being updated properly. This PR fixes those issues and auto generates the readme everytime we publish a new version.
1) Added a new bin file called readme. This setups everything we need to call the oclif readme command.
2) Modified the publish workflow to update the readme when we update the version.
The new format has quite a few differences, but overall I think it is actually easier to read. User experience should not be impacted in any meaningful way.
```
npm run readme
```
Example file of the new output. https://gist.github.com/mueschm/0d51abfc5a788376c1a1962afa41a527
=> Update Readme to Oclif 2

.github/workflows/cli-rc.yml, .github/workflows/publish.yml
The hook to update the website was being done when an rc was generated. This changes it so that it is done when we publish a new version of the CLI.
=> Moved website update hook to cli publish.

src/architect/account/account.utils.ts, src/commands/exec.ts, src/commands/logs.ts
Allows users to access their locally run instances without logging in
Added the following changes:
* exec and logs function:
- set auth_required() to false to allow use when not logged in
*account.utils
- Updated getAccount() to check if the user is logged in
- if not logged in, warn user and default to local account
=> Draft: Allow user to run exec without being logged in

docs/2-deployments/7-observability.md
Added a new docs page that explains how to use architect exec and logs. This provides a couple of basic examples showing how to use these commands.
1) Used Gatsby to veirfy the style
2) Ran through Grammerly to make sure it was grammatically correct.
=> Add docs for exec and logging.

src/commands/deploy.ts, src/commands/dev.ts, src/common/utils/deploy.utils.ts, test/commands/deploy.test.ts
Extend Deploy.utils to allow multiple secret-files to be ingested
The last file provided will always upsert any existing secrets, and any secrets passed via CLI will upsert all secret-files in the '*' key.
**Testing:**
With two secret files, you can run:
$ architect deploy --secret-file secrets1.yml --secret-file secrets2.yml
OR
$ architect deploy --secret-file secrets1.yml secrets2.yml
OR
$ architect deploy --secret-file secrets1.yml --secret-file secrets2.yml -s secret_key=secret_value
=> Multiple secret files

src/commands/dev.ts, src/common/docker-compose/index.ts, src/common/utils/docker.ts
On a remote deployment, kubernetes will restart  a service if there are issues with its health checks or if the container fails to start. Locally this does not happen. If a container fails to start then it just crashes. Health checks are generally ignored. The goal is to bring local deployments into parity with remote deployments.
1) Add a new function in the CLI that monitors each running service and checks their health and running state.
2) If a service fails we restart it and reattach the logging for it.
3) If the service becomes unhealthy we 
I created a sample app called Health that is as follows.
```
const express = require('express')
const app = express()
const port = process.env.PORT;
let stopService = false;
console.log(port.toString());
let pingCount = 0;
app.get('/ping', (req, …
```
=> Add restart for local services based on exit status or health

CHANGELOG.md, release.config.js
1. Reverted the changelog to make sense based on what is in master.
2. Disable changelog generation for non main branches.
=> Disable changelog for non main builds.

src/commands/dev.ts
Make sure that when `docker compose up` is run that orphaned containers are destroyed.
1) Remove the env that ignored orphans
2) Add the parameter that removes orphans
Used my health test from https://github.com/architect-team/architect-cli/pull/550
Added a service called `health2` and ran that. Stopped it then removed the service from the yml file. Started it again and only one instance was running.
=> Remove orphaned containers on startup.

src/common/docker-compose/index.ts
In some cases the health check can enter a race condition that seems to be occuring inside docker itself. This means an innocuous command that just checks all the containers can throw an error. The health watcher should not throw errors when this happens and instead should just keep chugging along. Just because a health check command fails does not mean we should kill dev.
Wrapped the inner loop of the health check in a try catch and ignore the errors. 
Same as https://github.com/architect-team/architect-cli/pull/550
=> Do not throw errors on health check.

docs/2-deployments/1-automated-previews.md
With the register command changes, we have switched over to `docker buildx` as the docker default image does not come with this we need to install the plugin ourselves. This updates the docs to show our customers how to do this as well.
=> Update gitlab CI docs to use buildx.

release.config.js
After looking at the logs it looks like the git command is happening before some of the other commands. Since most commands occur at the same step and they seem to match the order they were put in the config file, I am changing that order. This should fix it.
1. Update order of the plugins for semantic release.
2. Log the order to make it easier to debug in the future.
`node release.config.js`
```
{
branches: [
'main',
{ name: 'rc', prerelease: true },
{ name: 'arc-*', prerelease: true }
],
plugins: [
'@semantic-release/commit-analyzer',
'@semantic-release/release-notes-generator',
[ '@semantic-release/exec', [Object] ],
'@semantic-release/npm',
[ '@semantic-release/git', [Object] ]
]
}
```
`GIT_BRANCH=main node release.config.js`
```
{
branches: [
'main',
{ name: 'rc', prerelease: true …
```
=> Changed order of plugins to fix git happening too soon.

src/commands/register.ts, src/common/docker-compose/index.ts, src/dependency-manager/graph/node/service.ts, src/dependency-manager/graph/node/task.ts, src/dependency-manager/utils/refs.ts, test/dependency-manager/reserved-names.test.ts, test/dependency-manager/utils/refs.test.ts
The purpose of this PR is to restore the image name generation in the register command. Adding `reserved_name` changes the `ref` of a node to just that reserved name and that's it.Without a reserved name though, the ref would contain the component name, whether the node was a service or task node, and the name of the service or task that it represents. This information is required when creating an image to push to the registry
=> Ensure that image names are preserved when a reserved name is used

src/commands/platforms/create.ts, src/common/utils/kubernetes-platform.utils.ts
When running `platform:create`, a message will show notifying
the user of the latest version of K8 we suport (up to v1.23).
If the user tries to register a K8 cluster v.1.24.0 or higher,
an error will be thrown
=> Alert user on K8 version support

src/commands/secrets/download.ts, src/commands/secrets/upload.ts, src/dependency-manager/spec/utils/slugs.ts, test/dependency-manager/interpolation.test.ts, test/dependency-manager/utils/slug-splitters.test.ts
Our interpolation was using a forward lookahead for an unlimited amount of characters before, which could catch something like an `curl --fail localhost:3000/users || exit 1` in the service config. The `--` would fail the regex match, and therefore not find the edges of a service for the graph. The regex has been updated to take this into account, and a test was added
=> fixing interpolation if a service config string has a -- in it

src/commands/register.ts, src/common/utils/docker-buildx.utils.ts
A bug was found where running `architect register` on Windows and then on WSL2 would cause a failure. This was found to be because the buildx contexts that are generated are not compatible between OSs. The fix is to append the platform to the context name in order to make it unique per system.
1. Append the os name to each context.
2. Moved some of the logic from the register function into the buildx function to make it more clear what is being used where.
Smoke test: `npm run test`
Ran `architect register ./examples/hello-world/architect.yml` on both WSL2 and Windows on the same machine.
=> Fix incompatible builders between os on same system.

src/commands/exec.ts, src/common/docker-compose/index.ts
When running the exec command we now send back the correct status code for the downstream command.
Failed downstream command
```
muesch@Michael-PC:~/Architect/code/architect-cli$ architect-local exec -- cat nothasdf
? Select an account dev (Local Machine)
? Select a service cloud.services.registry
cat: can't open 'nothasdf': No such file or directory
Command failed with exit code 1: docker compose -f /home/muesch/.config/architect-local/architect/docker-compose/cloud.yml -p cloud exec cloud--registry cat nothasdf
Error: Command failed with exit code 1: docker compose -f /home/muesch/.config/architect-local/architect/docker-compose/cloud.yml -p cloud exec cloud--registry cat nothasdf
at makeError (/home/muesch/Architect/code/architect-cli/node_modules/execa/lib/error.js:60:11)
at …
```
=> Add status code on exit for exec local

src/commands/exec.ts
Looks like this is the only place in the CLI that we weren't using `token.token_type` yet - necessary for `architect exec` to work with personal access tokens (token_type is "Basic" for them).
=> Pass the proper auth header when using exec via token_type

src/common/docker-compose/converter.ts, test/commands/init.test.ts
Using the debug block instead of conditionals for the `architect init` command
=> debug block instead of interpolation

.madgerc, package.json, src/app-config/service.ts, src/architect/user/user.entity.ts, src/base-command.ts, src/commands/deploy.ts, src/commands/dev.ts, src/commands/doctor.ts, src/commands/environments/destroy.ts, src/commands/init.ts, src/commands/platforms/create.ts, src/commands/platforms/destroy.ts, src/commands/platforms/index.ts, src/commands/task.ts, src/commands/validate.ts, src/sentry.ts, test/commands/config/get.test.ts, test/commands/config/view.test.ts, test/commands/environments/index.test.ts, test/commands/link.test.ts, test/commands/platforms/create.test.ts, test/commands/register.test.ts, test/commands/unlink.test.ts, test/dependency-manager/validation.test.ts
This diff cleans up some of the Sentry code as well as fixes how it handles exit codes.
1. Migrated most code into the sentry class and out of base command
2. Added tests to make sure exit codes get set on error for regsiter
3. Cleaned up some of the logic to decouple Oclif and Sentry
4. Switched the debug logs to now use Oclif debug. We will most likely migrate off those, but this is not a blocker. To view the logs just put `DEBUG=architect:* ` before any command.
Worked on it in conjunction with Devin.
`npm run test`
`architect-dev register .
/examples/react-app/architect.yml --architecture not-real`
This will fail since the architecture is not real. Then check the error code with
`echo $?` which should return `1`.
You can also see the error logs appear in Sentry.
`architect-dev …
=> Sentry Refactor and Bug Fix

.github/workflows/publish.yml, src/commands/exec.ts, test/commands/exec.test.ts
Thanks to the beauty of StackOverflow, I found an easy way to run `architect exec` with no tty: https://superuser.com/a/1430883
I used the following test script to run exec:
```sh
#!/bin/sh
XDG_CONFIG_HOME=~/.config/architect/local/architect /Users/tyler/code/architect/architect-cli/bin/dev exec -a tyler-aldrich -e example-environment -- "sh -c \"ls -la && echo 'hi'\""
```
Running this on this branch now gives the following output:
```
~/code/architect/architect-cli (detect-notty-automatically*) » true | (setsid ./test-script.sh) 2>&1                                                                                  
stdin does not support tty and was automatically disabled, --no-tty should be used
total 68
drwxr-xr-x    1 root     root           116 Aug  4 18:33 .
drwxr-xr-x    1 root …
```
=> Automatically detect proper value for flags.tty if not explicitly set

.gitignore, release.config.js
This was crashing because the `.npmrc` file was not being ignored correctly and made a rebase not possible.
This should fix the issue.
=> Add back in back merge

src/common/docker-compose/index.ts, test/commands/dev.test.ts
Undoes the change [here](https://github.com/architect-team/architect-cli/pull/676/files#diff-c501db4ece42dfe6ff2e5e68da3e74b84a44bb1e6e14bbb53fc920376a11bc0cR183) as a liveness probe shouldn't be using HTTPS
=> fixing healthcheck liveness probe protocol for port/path

src/commands/dev.ts, src/common/docker-compose/index.ts
When we hit this code:
```typescript
try {
await compose_process;
} catch (ex) {
if (!is_exiting) {
throw ex;
}
}
```
it was possible for the `compose_process` to end (with an error that we throw) - but the process finishing with an error doesn't guarantee that containers get cleaned up. One container may hard-fail, the process ends, and other containers remain running.
To fix that, we now run:
```typescript
try {
await this.compose_process;
} catch (ex) {
if (!this.is_exiting) {
// Always call `docker compose stop` here - the process died so there's nothing to kill,
// need to call `docker compose stop` to clean up any remaining running containers.
console.error(chalk.red(ex));
console.log(chalk.red('\nError detected - Stopping running containers...'));
await this.stop();
}
}
```
to call …
=> Dev command leaves containers running when process exits with an error

src/common/docker-compose/index.ts, src/common/docker-compose/project.ts
Older versions of `docker compose` don't have a `ConfigFiles` key when running `docker compose ls`. I installed docker compose v2.2.3 from January and this key isn't yet available.
It's ideal to use this value directly if it exists, but if it doesn't, we fall back to manually searching the `LOCAL_DEPLOY_PATH` directory and matching the files there up with the results of `docker compose ls` (which still gives us the name of the compose file). 
Tested this on my Windows machine that has the older version of docker compose installed, and tested on my Mac that has the most up to date Docker, so the old path is working as it did prior and the new path now fixes the bug. 
Bug in question is https://sentry.io/organizations/architect-io/issues/3493163125/?project=6465948&referrer=slack
=> Fix getLocalEnvironment failing on older versions of compose without ConfigFiles

src/commands/exec.ts
`--` has a different but equally special meaning in PowerShell, and running `--` in a command causes PowerShell to treat it specially and it doesn't appear in the programs `argv`.
In order for `architect exec` to work nicely in PowerShell, there's only 2 (maybe 3) options:
1. Ask users to delete `architect.ps1` from wherever they npm install it. This makes it so `architect` on the CLI will use the cmd executable that doesn't have this issue.
2. Provide this error message so users can self-correct the -- behavior by escaping it
3. (not realistic) pray that NPM reverses the decision to include a special powershell script when publishing packages. As far as I can tell, this can't be disabled by us
The most realistic fix unless https://github.com/npm/cmd-shim changes is to just provide a …
=> Improve error message for Windows PS users

src/base-command.ts, src/commands/deploy.ts, src/commands/dev.ts, src/commands/environments/destroy.ts, src/commands/exec.ts, src/commands/logs.ts, src/commands/platforms/create.ts, src/commands/platforms/destroy.ts, src/commands/secrets/upload.ts, src/commands/task.ts, src/commands/unlink.ts, src/common/utils/oclif.ts, test/commands/platforms/create.test.ts
please see https://gitlab.com/architect-io/architect-cli/-/issues/496
=> 496 consistent boolean flags

src/commands/init.ts, src/common/utils/git/helper.ts
Added checks to project creation function to check that Docker/Compose and Git are all installed before the function/user can proceed
* Added `RequiresGit` decorator to check that `git` is installed
* Added `RequiresGit` and `RequiresDocker` decorators to project init function
* Uninstalled `git` to check that an error would be thrown
* Reinstalled `git` to ensure that error was no longer thrown
=> adding decorator to check that git/docker are installed for project init

src/commands/dev.ts
Previously, we'd see something like this if two ingresses were configured (test and test-2)
```
Building containers... done
Once the containers are running they will be accessible via the following urls:
https://test.localhost.architect.sh:443/ => hellow-world--app
https://localhost:443/ => gateway:443
https://localhost:8080/ => gateway:8080
https://localhost:50001/ => hellow-world--app:8080
https://localhost:50002/ => hellow-world--app-2:8080
```
Now, we get the proper output:
```
Building containers... done
Once the containers are running they will be accessible via the following urls:
https://test.localhost.architect.sh:443/ => hellow-world--app
https://test-2.localhost.architect.sh:443/ => hellow-world--app-2
https://localhost:443/ => gateway:443
https://localhost:8080/ => …
```
=> Fix issue causing only 1 service with an ingress to have it's URL displayed in `architect dev`

src/common/docker/helper.ts
I wasn't able to reproduce this error myself (On wsl2 without the daemon running, `docker info` still works) - however, TJ did get an error here:
```
module: @oclif/core@1.9.0
task: toCached
plugin: @architect-io/cli
root: /home/tj/code/cli
See more details with DEBUG=*
(node:25875) Error Plugin: @architect-io/cli: Command failed with exit code 1: docker info --format {{json .}}
The command 'docker' could not be found in this WSL 2 distro.
We recommend to activate the WSL integration in Docker Desktop settings.
```
which clearly means there's a way for `which.sync('docker')`` to return true, but `docker info` doesn't work, so we now try/catch so the user gets a better error message.
=> Add safeguard to `docker info` call to prevent errors when daemon isn't running

src/commands/dev/index.ts, src/commands/dev/list.ts, src/common/docker-compose/index.ts, src/common/docker-compose/template.ts, test/commands/dev/index.test.ts, test/commands/dev/list.test.ts
**Note: I have this set to merge into https://github.com/architect-team/architect-cli/pull/692 just so the diff is cleaner, but https://github.com/architect-team/architect-cli/pull/692 should be merged first and this can then point at rc instead.**
Adds the `architect dev:list` command which displays your active dev environments, their containers, and those containers statuses.
Example output:
```
~/code/architect/architect-cli (dev-list) » architect dev:list                    
┌────────────────────┬─────────────────────┬─────────┐
│ Environment        │ Containers          │ Status  │
├────────────────────┼─────────────────────┼─────────┤
│ arc-hellow-world-1 │ hellow-world--app   │ running │
│                    │ hellow-world--app-2 │ running │ …
```
=> Add dev:list command

src/commands/register.ts, src/common/docker/helper.ts, src/dependency-manager/utils/errors.ts, src/sentry.ts, test/commands/register.test.ts
Log the error from `docker buildx bake` and exit the process (with whatever error code buildx bake returned with) so that we don't get sentry logs about this.
As we're just running a docker command here, the most likely cause of failure is somebody trying to register a Dockerfile that can't be build properly (for any reason - syntax errors, copying a file that doesn't exist, running a command that fails, etc). This isn't something we can fix, so we shouldn't be throwing an error and should just be informing the user.
=> Prevent `architect register` failures in docker buildx from throwing Sentry errors

README.md, package-lock.json, package.json, src/commands/dev.ts, src/commands/exec.ts, src/commands/logs.ts, src/commands/task.ts, src/common/docker-compose/index.ts, test/commands/components/index.test.ts, test/commands/task.test.ts
Default project name is now the name of the first component in the `architect dev` command. If you run multiple components at once (e.g. `architect dev architect.yml architect-2.yml`), the first architect.yml's component name is used. (Open to suggestions here, but prior it was always named `architect` so this is still better imo).
When using the `-e` flag, that still overrides this default, so `architect dev -e foobar` will run `docker compose ... -p foobar up`.
If you run `architect dev` on the same component multiple times, each subsequent compose is given a number (e.g. `hello-world`, `hello-world-1`, `hello-world-2`, etc). Used this instead of a UID/some random number because each instance creates new containers and we want to re-use those containers when possible. If we always …
=> Change default project name for `architect dev`, allowing multiple envs w/ same name

src/dependency-manager/graph/index.ts, src/dependency-manager/manager.ts
Lock the generated graph object once it has been created. 
`DependencyGraph` was converted to `DependencyGraphMutable`
`DependencyGraph` now is `Readonly<DependencyGraphMutable>`
This gives us full typescript linter support as well as runtime verification.
Run `npm run test`
Tested the `dev`, `register` and `deploy` commands to make sure nothing broke.
=> Make graph immutable

src/common/docker-compose/index.ts
* `docker rm $(docker ps -aq) -f`
* `architect dev ...`
=> fixing info function when no containers are running

src/common/docker-compose/index.ts, src/dependency-manager/spec/transform/component-transform.ts, test/commands/dev/index.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/interpolation.test.ts
Traefik by default assumes that the downstream system is http. This is not always true since some systems handle their own https connections. 
This does two main things.
1. Tell Traefik to ignore self signed certs in the downstream.
2. Tell the load balancer which protocol to use if its defined. This will defer to the protocol field but also attempt to parse the url if available.
Tested with our local stack and everything seems to be working.
=> Fix https to https issue

src/commands/exec.ts, src/common/docker-compose/index.ts, src/common/docker/buildx.utils.ts
Saw Michael ran into this issue on Friday and noticed that the tty testing I was doing a month or so back was almost exclusively in the `runRemote` method and I didn't verify that local worked. We always passed `true` which attempted to call `process.stdin.setRawMode(true)`, which only works if `process.stdin` is a tty ReadStream.
sentry error: https://sentry.io/organizations/architect-io/issues/3598979632/?project=6465948&referrer=slack
=> Dont always try to setRawMode in runLocal, only do so if tty

src/commands/dev/index.ts, src/common/docker-compose/index.ts, test/commands/dev/index.test.ts
Reverts the project name to the old name syntax. 
1. Revert the default project name back to `architect`
2. Added check for env name conflict
3. Return information about how to deal with the conflict
Ran two dev commands without specifying the env. The second one produced the image below.
Added 1 unit test.
=> Revert project name back to old system

src/commands/dev/list.ts, test/commands/dev/list.test.ts
Dev list allows a user to understand what is running in the background, but if you want to automate behavior based on it, you need to create a special parser to read the data. This allows us to output the same format in json which is much easier to read.
Add `--format` to dev list. Default behavior does not change, but you can also choose json.
Added 1 new unit test
Tested it out
=> Add output type to dev list

src/commands/scale.ts
Stops scale from showing interpolation values as services.
=> Do not display interpolation as an option

src/commands/dev/list.ts
update output for json dev empty to be empty set
---
Tested just to be sure the changes will only affect output when using  json format flag specifically.
```
architect-local dev:list --format JSON
{}
architect-local dev:list --format json
{}
architect-local dev:list --format table
There are no active dev instances yet. Use `architect dev` to create one.
architect-local dev:list --format TABLE
There are no active dev instances yet. Use `architect dev` to create one.
architect-local dev:list
There are no active dev instances yet. Use `architect dev` to create one.
```
=> always print json format when json format flag is specified

src/commands/dev/index.ts, src/commands/dev/stop.ts, test/commands/dev/stop.test.ts
Note: This is only a problem on Unix environments. Windows sockets get cleaned up automatically when the process that spawned them is closed, so closing the powershell / cmd window with the `architect dev` process closes the socket. 
To reproduce the issue on Unix systems:
- Run `architect dev`, once it starts, close the terminal window
- In a new window, `architect dev:stop` will throw an error because the socket exists but nobody is listening.
- If you stop the docker containers yourself, and run `architect dev` again, it blows up because the socket already exists.
- Only workaround without this change is to manually `rm` the socket
=> Fix issue where if the terminal is closed, the socket isnt cleaned up but still exists

src/commands/dev/index.ts, src/commands/register.ts, src/common/docker/helper.ts, src/dependency-manager/utils/errors.ts
I checked existing ArchitectError's to see if any are things we should actually be alerted of, and no existing ArchitectErrors or errors that extend ArchitectError were something actionable. They are all handled exceptions that report useful info back to the user, so we don't need to receive alerts about them.
=> Default to track=false for ArchitectError

src/architect/account/account.utils.ts, src/architect/user/user.utils.ts, src/commands/register.ts, test/commands/register.test.ts, test/mocks/register/architect.yml
Closes: https://gitlab.com/architect-io/architect-cli/-/issues/550  
When an invalid account name is specified in architect.yml, we inform the user with an error message and allow them to choose one of their existing accounts. 
Search for the component account in user's list of accounts. If it's not found, print out the error message.
- Change the component name in an architect.yml to `name: invalid-account-name/hello-world`
- Run `architect-local register .`
=> Allow account selection if component account is not found

src/commands/task.ts, test/commands/task.test.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/559.  
Fix `could not find docker compose file` in tasks
Reverted the project_name variable when running task locally
Run Scheduled_tasks example locally and remotely
=> 559 fix tasks

src/dependency-manager/manager.ts, test/dependency-manager/graph.test.ts, test/dependency-manager/interfaces.test.ts, test/dependency-manager/validation.test.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/554.  
Re-enable the check for non-http/https protocols through gateway.
If ingress has subdomain, check if the protocol is either http or https. Otherwise, throw an error.
Have 2 components:  
Component 1   
```
name: component
dependencies:
dependency: latest
services:
app:
interfaces:
main: 
port: 8080
protocol: tcp
environment:
API_URL: \${{ dependencies.dependency.interfaces.api.url }}
interfaces:
app:
url: \${{ services.app.interfaces.main.url }}
ingress:
subdomain: app
```
Component 2    
```
name: dependency
services:
api:
interfaces:
api: 443
interfaces:
api: \${{ services.api.interfaces.api.url }}
```
This will fail because the protocol `tcp` in component 1 is exposed to public through ingress. If you comment out the …
=> 554 re-enable http/https validation

src/commands/environments/create.ts, test/commands/environments/create.test.ts, test/utils/mocks.ts
Please see https://gitlab.com/architect-io/architect-cli/-/issues/556
To enable cleaner CI configurations and to ensure that jobs don't pass on real errors, we should only warn on 409s when creating an environment. 
add validateStatus to environment:create command to manually append 409 as a passing status code. Add warning if http reply status code is 409.
```typescript
create_duplicate_environment
.env({ ARCHITECT_CLUSTER: mock_cluster.name })
.command(['environment:create', mock_env.name, '-a', mock_account.name])
.it('should print warning when an environment name is already in use for an account', ctx => {
expect(ctx.stderr).to.contain(`Unable to create new environment '${mock_env.name}'. Environment name already in use for account '${mock_account.name}'`);
});
```
TODO?
=> 556 ignore 409 status for env create

src/dependency-manager/spec/utils/slugs.ts, test/dependency-manager/utils/slug-validators.test.ts
Adds a validator for account names, part of https://gitlab.com/architect-io/architect-hub/-/issues/579
* Added a validator for case-insensitive slugs to be used as a looser validator for account names or others
* Added tests
=> validator for looser validation on account names

src/common/docker-compose/index.ts, src/common/docker-compose/template.ts
Please see https://gitlab.com/architect-io/architect-cli/-/issues/561
If your liveness probe fails before it hits your service (e.g. you don't have curl installed on the container and it's trying to curl a URL), it silently fails and will just restart your container without any indication as to why. We can possibly use docker status or similar to get the reason the probe failed and can more clearly surface the issue to the user so that they know what is going wrong.
Add  Health property to DockerInspect  interface.  Check for failing liveprobe, and conditionally fetch logs from docker inspect. print to screen.
N/A
=> 561 log errors when liveness probe fails

src/commands/dev/index.ts, src/common/utils/deploy.utils.ts, test/commands/dev/index.test.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/566.  
Allow `architect dev` command to pull in secrets from an environment to be used for local dev.
Get secrets from a production environment and merge to other component secrets.
- Create a secret in a production environment
- Use that secret in your application `architect.yml`
- Run `$ architect dev . --secrets-env=my-environment -a my-account`
=> 566 local dev secrets

src/commands/clusters/create.ts
Remove type `kubernetes` from cluster registration example since it is no longer used.
=> Remove type kubernetes from cluster registration

src/commands/register.ts, test/commands/register.test.ts
please see: 
https://gitlab.com/architect-io/architect-cli/-/issues/529
>architect dev doesn't require you to specify an architect.yml and will assume you mean ./architect.yml. architect register doesn't do this - if you run architect register it will just do nothing, and you need to run architect register . instead. We should update the register command to support being run with no path similar to dev.
Moved path resolution into run method to avoid having to resolve twice. 
Moved deduplication as last step after paths have been resolved.
Set default path as `./architect.yml` (same as architect dev command)
```javascript
mockArchitectAuth()
.stub(fs, 'move', sinon.stub())
.stub(ComponentRegister, 'registerComponent', sinon.stub().returns({}))
.stdout({ print })
.stderr({ print }) …
```
=> 529 default register path

src/sentry.ts
Please see https://gitlab.com/architect-io/architect-cli/-/issues/567
Sentry transactions for the CLI project assigns command flags under Additional Data. Additional Data is not indexed for search, so there is no way to filter search results for a particular flag value used. Eg., wanting to see architect dev/deploy commands that have used the -i flag.
Update sentry startTransaction to add command flags passed by argument to CLI as tags to sentry.
Move logic for setting additional data into start sentry transaction.
- `npm run test`
-  `architect environments`
-  `architect environments -a architect`
N/A
=> 567-add-additional-data-as-tags

src/common/docker-compose/index.ts, test/commands/register.test.ts, test/mocks/superset/architect.yml
Fixes registering a component with a service that includes a reserved name (https://gitlab.com/architect-io/architect-cli/-/issues/579)
* Passing `architect_ref` to `getImage` rather than just `ref`
* Added test that registers the superset
=> Fixing register for services with reserved names

src/commands/login.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/580.  
Failure to login in the `non-tty environment` will send the error to Sentry. Since this is a handled error, we want it to be an ArchitectError.
Throw an ArchitectError instead of Error
=> Update error type in login

.github/workflows/test-deploy.yml
Updated when TJ found that no workflows were triggered by [this PR](https://github.com/architect-team/architect-cli/pull/780)
* Updated the condition for the remote deployment job to use the proper `github` context property
=> updating the remote deployment condition

src/sentry.ts
add null-safe chain to make referencing user input via either invalid file parsing, or cli stdio directly more safe.
filter out potentially undefined values coming from stdio or file parsing directly.
please see: https://gitlab.com/architect-io/architect-cli/-/issues/595
architect dev using an empty architect.yml configuration file
N/A
N/A
=> add nullsafe chain, and filter out potential null

src/commands/deploy.ts, test/commands/deploy.test.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/598 by also printing the URL when the component(s) specified to be deployed don't include a tag
* Checked the returned cert data to see if it matches either just the component name or the component and tag name
* Added a test for the case where the component tag isn't specified
* ```sh
ryan@ryan-ThinkPad-P53s:~/Code/architect-cli$ architect deploy -e do-k8s hello-world react-app --auto-approve
Creating pipelines... done
hello-world Deployed
react-app Deployed
Deploying... done
Deployed services are now available at the following URLs:
https://hello.do-k8s.architect-ryan.dev.arcitect.io
https://app.do-k8s.architect-ryan.dev.arcitect.io
```
=> Remote deployment url fix

.github/workflows/test-deploy.yml, examples/stateful-component/frontend/Dockerfile
Adds a test to the superset remote deployment that checks that communication is enabled between services where it should be enabled. Closes https://gitlab.com/architect-io/architect-cli/-/issues/587
Check passing on previous PR targeting `main`: https://github.com/architect-team/architect-cli/actions/runs/3808982183/jobs/6480000852
=> Superset test communication enabled

src/commands/dev/index.ts, src/dependency-manager/utils/files.ts, test/commands/dev/index.test.ts
Please see:
https://gitlab.com/architect-io/architect-cli/-/issues/582
https://gitlab.com/architect-io/architect-cli/-/issues/602
Add a check to see if yaml is empty before parsing. 
* Throws error if empty.
Add try catch around dev buildImage function. 
* Catch identified error message and display message to screen.
run dev command against empty architect.yml file. See error message, and no sentry submission
run dev command with a dockerfile containing an exception. See error message, and no sentry submission.
```
test
.timeout(20000)
.stub(ComponentBuilder, 'loadFile', () => {
return '';
})
.stub(Dev.prototype, 'failIfEnvironmentExists', sinon.stub().returns(undefined))
.stub(Dev.prototype, 'runCompose', sinon.stub().returns(undefined))
.stub(Dev.prototype, 'downloadSSLCerts', …
```
=> 582 602 expected docker compose err

src/commands/platforms/create.ts, src/commands/platforms/destroy.ts
These deprecation warnings were wrong - if you run `architect platform:create` it tells you to run `cluster:register` but the real command is `clusters:register` (same with deregister with any of the `platform:delete` equivalents)
=> Incorrect cluster command when warning about deprecated platform command

test/integration/schedule-tasks/Dockerfile, test/integration/schedule-tasks/Readme.md, test/integration/schedule-tasks/architect.yml, test/mocks/superset/architect.yml
When removing examples from the superset we broke the ci because we partially broke being able to deploy the superset. This fixes those issues.
Add back in support for tasks
Was able to register and deploy the superset.
=> Fix superset

src/architect/cluster/cluster.utils.ts, src/common/utils/agent-cluster.utils.ts
Send up cluster information to allow us to know if it is a local cluster.
1. Add a function that can get a server for a context.
2. Send up the server to the API.
Tested alongside https://gitlab.com/architect-io/hub-api/-/merge_requests/700
=> Pass up cluster information to allow it to work locally

src/dependency-manager/spec/utils/slugs.ts, test/commands/validate.test.ts, test/dependency-manager/validation.test.ts
Closes: https://gitlab.com/architect-io/architect-hub/-/issues/664
The slug description that verifies account name, cluster name, etc states that underscores are allowed but the regex contains no underscores. We want to remove the mention of underscores in that slug description.
Remove mention of underscores in architect slug description.
=> Update architect slug description

src/architect/environment/environment.utils.ts, src/commands/environments/ingresses.ts, test/commands/environments/destroy.test.ts, test/commands/task.test.ts
Added a command to log ingress URLs so the URLs can more easily be pushed into PR comments on preview environments.
New command:
```
$ architect environment:ingresses <environment-name> -a <account-name>
https://api.localhost.architect.sh
https://app.localhost.architect.sh
```
* https://github.com/architect-team/architect-documentation/pull/39
* https://github.com/architect-team/documentation/pull/3
=> Added command to log ingress URLs associated with an environment

.github/workflows/publish.yml, package.json
In our `package.json` file we specify a minimum supported version of node for our CLI. Though right now this just appears as a warning. In order to make it an error we need to enable `strict engine` mode which can only be done in the `.npmrc` file. 
1. Make sure the `.npmrc` file is packed into the app.
2. Make sure we write our token to the home directory version of `.npmrc` so it does not get committed into our repo during a release. (Tested this locally but we should monitor for a problem during first release in case we need to rotate the key because something went wrong)
3. Also added the deprecated `package.json` flag for really old versions of npm.
Test all the changes locally. Our checks actually worked using `npm link` because the file existed. Also double checked that the …
=> Enable strict engine for npm

src/commands/clusters/create.ts, test/commands/clusters/create.test.ts, test/commands/platforms/create.test.ts
Make sure that a cluster name is unique before anything is created.
1. Ask for account before cluster name now
2. Make sure cluster name is unique or tell user to keep trying
3. Removed old agent specific test
4. Rename some functions in test to make more sense now
5. Added tests
1. Add unit tests
2. Went through creation flow 
3. Checked it fails properly for flags
4. Checked it fails properly for prompt
=> Make sure a cluster name is unique before creation

src/dependency-manager/spec/utils/spec-docs.ts
Goes with this Docs PR: https://github.com/architect-team/documentation/pull/6
=> add link to the vscode extension in the reference/architect.yml page

src/commands/dev/restart.ts, src/common/docker-compose/index.ts, test/commands/dev/index.test.ts, test/commands/dev/restart.test.ts, test/commands/dev/stop.test.ts
Adds the `dev:restart` command to rebuild or just restart a service running via `architect dev`
ex. `architect dev:restart --build hello-world.services.api` will rebuild the image for the api service of the hello-world component and restart it without needing to restart `architect dev`.
This also bumps the version of traefic to v2.9.8 to make use of the `providers.docker.allowEmptyServices` flag, which helps make the UX less confusing (preventing traefic from "forgetting" about the service until after a liveness probe passes, which also enables us to make a custom traefik error page to inform the user that nothing is broken)
Two biggest test cases are
- A service without a liveness probe
- A service with a liveness probe
A service that starts quickly and has no liveness probe will be …
=> Add dev:restart command

src/commands/dev/index.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/586.  
Update description for environment in `architect dev`
Set a flag for environment in `dev` command with the new description instead of using `Environment.flags`.
=> Change env flag description for architect dev

src/common/docker-compose/converter.ts, test/mocks/init-compose.yml
Docker compose import no longer breaks when the depends_on is a dictionary instead of an array.
Fixed the issue
```
services:
web:
build: .
depends_on:
db:
condition: service_healthy
redis:
condition: service_started
redis:
image: redis
db:
image: postgres
```
Also modified a unit tests data to make sure this works.
=> Depends on now supports dictionaries

src/commands/dev/index.ts
https://gitlab.com/architect-io/architect-cli/-/issues/630
The `serverStatus` object has a key with the service IP/port and a status like 'UP'. When there's a liveness probe and it's failing, it looks like this:
```ts
serverStatus: { '': 'UP' },
```
so we incorrectly said it was healthy just because UP existed. But, UP exists because we tell traefik `allowEmptyServices` now.
Once the service has URL:
```ts
serverStatus: { 'http://172.18.0.2:8080': 'UP' },
```
the liveness probe actually passed and we can now say it's healthy and open links in the browser.
=> Prevent liveness probes causing dev to think something is healthy immediately

src/dependency-manager/utils/parser.ts, test/dependency-manager/components.test.ts
So we sometimes use redacted secrets and run validation. This allows redacted secrets to be valid for `parseUrl`. I am not 100% satisfied with this solution, but this can be reconsidered when we come back to configuration.
1. Allow `*`'s as a valid input for parseUrl
2. Added a missing unit test
Created `arc-databases-2` to test on the api and it all works.
=> Databases redacted secrets

src/architect/project/project.utils.ts, src/commands/init.ts, test/commands/init.test.ts
Add `starter` flag to the init command to specify which starter project to use.
`architect init --starter Go`
1. Added starter flag
2. Add basic test case
Created projects using each method to make sure nothing broke.
Created project using current command.
`npm run test`
=> Add starter flag to init command

package.json
Make incompatible with version 12 of nodejs. This version has been deprecated.
Change engine version
Run npm install on version 12 of nodejs
```
muesch@Michael-PC:~/Architect/code/architect-cli$ npm install
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for @architect-io/cli@1.36.0: wanted: {"node":">=14"} (current: {"node":"12.22.12","npm":"6.14.16"})
npm ERR! notsup Not compatible with your version of node/npm: @architect-io/cli@1.36.0
npm ERR! notsup Not compatible with your version of node/npm: @architect-io/cli@1.36.0
npm ERR! notsup Required: {"node":">=14"}
npm ERR! notsup Actual:   {"npm":"6.14.16","node":"12.22.12"}
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/muesch/.npm/_logs/2023-03-22T17_57_14_031Z-debug.log
```
=> Require nodejs version of 14 or greater

src/commands/init.ts
Docker should not be required to generate a starter project.
Remove docker required annotation
Ran tests locally.
1. Stop docker
2. Run architect init
3. Profit
=> Remove docker as required for init

src/common/docker-compose/converter.ts, test/commands/init.test.ts, test/mocks/init-compose.yml
Closes https://gitlab.com/architect-io/architect-cli/-/issues/645  
Fix issue with build args value that occurred when converting a docker-compose.yml to architect.yml.
If build args is a map, cast each value to string.
docker-compose.yml  
```
version: "3"
services:
app:
build:
context: .
args:
INT_ARG: 1
BOOL_ARG: true
```
Run `architect-local init --from-compose=docker-compose.yml test`.   
Should generate the following architect.yml 
```
name: test
services:
app:
build:
args:
INT_ARG: '1'
BOOL_ARG: 'true'
context: .
reserved_name: app
```
=> Fix build args integer issue

src/common/utils/deploy.utils.ts, src/common/utils/secret/helper.ts, test/commands/dev/index.test.ts
Closes https://gitlab.com/architect-io/architect-cli/-/issues/648.  
Fix rounding issue when reading local environment variable with `dotenv`.
If the secret value get rounded when casting to a number, use its string format instead.
Export an environment variable    
$ export ARC_world_text=1232456789.1232456789   
Run hello-world example    
$ architect dev   
I tested it this way instead of using the `dotenv` command, `dotenv -e .env architect dev`, because the new code doesn't seem to be picked up.
Test remote   
Use package `"@architect-io/cli": "1.37.0-arc-mary.1"` in the API.    
$ architect-local register  
$ architect-dev register  
Deploy it with the following `world_text` value
=> 648 rounding number

src/commands/dev/index.ts
TIcket: https://gitlab.com/architect-io/architect-cli/-/issues/644 
This prevents _most_ cases of getting `ERR_UNSAFE_PORT` errors from Chrome/Firefox/etc. if the user happens to choose a port that browsers disallow connections to.
A full list of disallowed ports is browser dependent - [Chrome](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc) and [Firefox](https://www-archive.mozilla.org/projects/netlib/portbanning#portlist) examples here. Ports 1-1023 are [Well-known ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports) and many are reserved for specific services, so by forcing users to choose ports >= 1024 and <= 65535 the chance of selecting a well-known port that is blocked is less likely.
=> Require dev port selected is 80, 443, or between 1024-65535 

src/commands/deploy.ts, src/commands/register.ts, test/commands/deploy.test.ts, test/commands/register.test.ts, test/mocks/deprecations/liveness-probe-path-port.architect.yml
Warn the user if the component they register or deploy uses liveness_probe `path` and `port`. I set the removal date to be October of 2023 but do let me know when is the best time. Also, we need to merge the docs first. 
Add to the hello-world service:
```
liveness_probe:
port: 3000
path: /
```
Then run
- $ architect-local register
- $ architect-dev register   
- $ architect-deploy hello-world  
https://github.com/architect-team/documentation/pull/36
=> 649 liveness probe port path

src/architect/account/account.utils.ts
Allow to run an exec command locally without needing to go through prompts
Return account `dev` when requested
- Go to springboot starter project
- run `architect dev`
- run `architect exec --account dev springboot.services.app -- mvn compile`
=> Fix local exec

src/architect/cluster/cluster.entity.ts, src/architect/deployment/deployment.entity.ts, src/commands/deploy.ts, src/common/utils/deploy.utils.ts
Closes https://gitlab.com/architect-io/hub-api/-/issues/493.   
Warn the user when cluster deployment is deleted.
Add a check for deleted cluster deployment.
- Register your own cluster and create an env
- Go to cluster `Apps` and uninstall `Service Mesh`
- Deploy the hello-world component `architect-local deploy hello-world -e env --auto-approve`
=> Warn for deleted cluster deployment

src/architect/deployment/deployment.entity.ts, src/commands/deploy.ts, src/commands/register.ts, test/commands/deploy.test.ts, test/commands/register.test.ts, test/mocks/deprecations/liveness-probe-path-port.architect.yml
Reverts the revert here https://github.com/architect-team/architect-cli/pull/898 and fixes the problem with a new commit https://github.com/architect-team/architect-cli/commit/7c6d5fb8942b2442cb1fbac74fb603cbd705f9c5.
Environment deployments don't have a `component_version` and our type wasn't correct, so this bug wasn't caught initially.
=> Unrevert liveness probe warnings

src/commands/dev/index.ts
We weren't properly parsing the component name when creating `linked_components`, so if the component name was `test/flask`, we set the `linked_components` as `{ 'test/flask': './architect.yml' }`, but would later look up `flask` with no account name and found nothing.
=> Fix bug when running dev with a component that still has an account name in the component name

README.md, architect-yml.md, package-lock.json, package.json, src/dependency-manager/schema/architect.schema.json, src/dependency-manager/spec/component-spec.ts, test/integration/stateless-component/architect.yml, yarn.lock
Customers want to deploy different versions of their app at different times. This change allows you to use a secret as tag in the dependency block. Now you can change which version of a dependency will be used during deploy time.
Allow tags to be secrets.
Did a full end to end test locally and deployed different tagged components.
=> Allow secrets to be used as tags

src/dependency-manager/config/service-config.ts, src/dependency-manager/spec/service-spec.ts, test/dependency-manager/interpolation.test.ts
Allows the `ip-whitelist` to be submitted as a comma-separated list of IPs and CIDRs
Added a test for the new format
=> allowing an ip whitelist to be submitted as a comma-delimited string of ips/cidrs

.github/workflows/test-deploy.yml
Re-enabling the network policy test now that we can create an env from the command line with zero-trust enabled: https://gitlab.com/architect-io/architect-cli/-/issues/583
The port number and error message we were looking for both seem to have been changed since this test last worked - I tested this against an environment with zero-trust enabled and disabled to make sure the test worked correctly:
(Environment with zero-trust enabled is `ztrust`, the default disabled zero trust is `example-environment`)
```
~/code/architect/architect-cli (reenable-network-policy-test*) » architect-dev exec -a test-tyler -e ztrust superset.services.stateful-api -- sh -c  "curl --connect-timeout 10 --insecure -L -I http://hello-world--api:8080/ || true" > network_policy_test.txt 2>&1 </dev/null
if [[ $(cat …
```
=> Re-enable network policy test
